[package]
name = "ratelmq"
version = "0.0.1"
authors = ["Wojciech Wilk <galhadpl@gmail.com>"]
edition = "2018"
readme = "README.md"
homepage = "https://ratelmq.com"
repository = "https://github.com/ratelmq/ratelmq"

[dependencies]
tokio = { version = "0.3.3", features = ["full"] }
bytes = "0.6.0"
